### ISSUE TITLE
Trade Pairs

### ISSUE THREAD

**Issue by charnasol** [3s3s/opentrade#10]
Hi

This is missing from set up/install and would be great to be able to add them without custom coding it. Thanks

**Comment by 3s3s** [comment]
Readme updated. Try it now

**Comment by vitorgamer58** [comment]
![Alt](http://ap.imagensbrasil.org/images/2018/03/21/Screenshot_585.png)
I found this piece of code that seems to say something about adding a coin, maybe it has an admin panel where it's easy to add and remove coins.

**Comment by 3s3s** [comment]
The first registered user have access to admin panel where it is possible to add coins. Please read new readme file

**Comment by vitorgamer58** [comment]
the new readme? ok, I did a pull request on Branch Test updating the redme for a dependency that was missing.

**Comment by 3s3s** [comment]
I took your changes into account.

**Comment by vitorgamer58** [comment]
is it giving a mistake when I register, apparently the exchange can not send email, could I get the file where I can configure the sending of smtp mail? I searched the code and did not find it. thank you.

**Comment by 3s3s** [comment]
You can change this constants https://github.com/3s3s/opentrade/blob/master/server/constants.js#L10
Mail content can be changed here
https://github.com/3s3s/opentrade/blob/master/server/modules/mailer.js

**Comment by vitorgamer58** [comment]
I still think something is missing, for example, the source email password, how will the exchange send email without the source email password?

I am having problems in the registration area because no email is sent, it gives error.

**Comment by 3s3s** [comment]
smtp protocol does not require passwords.
You should send email from your own domain (not from gmail)
This is you error:
exports.NOREPLY_EMAIL = "vitorgamer58@_gmail.com_"

**Comment by 3s3s** [comment]
You need to register domain and A-record for your domain should point to your IP address (address from where you will send emails)

**Comment by vitorgamer58** [comment]
I created a .tk domain and did DNS right, I changed it to vitorgamer58@bolsotrade.tk and I restarted the exchange, so I'm getting the same error

`error on connectMx Error: can not connect to any SMTP server`

but something that is very confusing for me is that I made the change you said and when I try to register with the email of the outlook he gives it.

```
Error on connectMx for:  { exchange: 'outlook-com.olc.protection.outlook.com',
  priority: 5 } { Error: connect ETIMEDOUT 104.47.5.33:25
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.47.5.33',
  port: 25 }
```

and when I try with my Gmail email

```
Error on connectMx for:  { exchange: 'alt4.gmail-smtp-in.l.google.com', priority: 40 } { Error: connect ETIMEDOUT 108.177.14.26:25
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '108.177.14.26',
  port: 25 }

```

If you want to look at my site
https://bolsotrade.tk:40443

**Comment by 3s3s** [comment]
Seems problem in your vps hosting provider. Some providers are blocks outgoing smtp traffic to port 25.

**Comment by vitorgamer58** [comment]
you are having a great patience with me in, kkkkkk, sometimes it seems so simple, as I did not succeed tried in my vps of the vultr, without success, did what you spoke with the domain and without success, read in an article that vultr blocks port 25 by default, I'm having to send a ticket and ask for the release.

**Comment by jonasess** [comment]
Hello .i have problem in recaptcha i added the private key of recaptcha to private_contacts.js but whenever i run the board and try to log in it shows that there's an error in recaptcha
I tried many keys but non of them worked . any solution for this?

**Comment by jonasess** [comment]
Whenever am trying to regester a new account i get Bad Request Something wrong ((

**Comment by 3s3s** [comment]
you need to setup recaptcha. Without it exchange will not work.

**Comment by charnasol** [comment]
He is trying to finish setting up opentrade for our exchange. If you can assist him with whatever recaptcha error he is getting, we can finish

**Comment by jonasess** [comment]
the recaptcha doesn't work at all . as i said i tried many secret key of google recaptcha but still am getting same issues

**Comment by jonasess** [comment]
recaptcha problem solved

**Comment by vitorgamer58** [comment]
All right, I was able to set up, but I got an error trying to add a coin.
![alt](http://ap.imagensbrasil.org/images/2018/03/23/Screenshot_599.png)

**Comment by jonasess** [comment]
Anyone have an idea on which file i have to deal with to change the open trade to a domain name instead of ip address and port?

**Comment by vitorgamer58** [comment]
yes, to change the port you must edit the file constans.js on line 16, to use a domain name just buy a domain.
https://github.com/3s3s/opentrade/blob/master/server/constants.js#L16

**Comment by jonasess** [comment]
I already have a domain name and it's pointed to another website (board) . i want to switch . instead of pointing the domain name on that board i want to point it on opentrade . in other side i will move the other board on the port 4440 .

**Comment by vitorgamer58** [comment]
I confess that I am not very good with configuration of this type, but the opentrade works independently of the NGIX or Apache

**Comment by jonasess** [comment]
nginx is used for configuration of server to point the domain name on the website .
so when you type www.example.com . that website appears . after installing opentrade . to access to opentrade instead of typing www.example.com you have to type www.exampe.com:40443
so with port you access to open trade without port you access to the other website .
am trying to take that website down and replace it with opentrade . so whenever you type www.exaple.com opentrade will appear .
The previos dev who set up the website used nginx to point the server to that website.

**Comment by vitorgamer58** [comment]
does not need much, just uninstall ngix, configure the opentrade port to 443 and get some way to http://yourdomain.com be redirected to https://yourdomain.com because when you put port 443 and enter via https there is no need to put yourdomain: 443 is the same as http with port 80

**Comment by vitorgamer58** [comment]
Add coin erro
```
INSERT INTO sessions VALUES  ('+n68Dllx8Qt6deayjqEjK/19gfZN6n0DDy/vDO5EsW0%3D', '1521829066500', '1')
UPDATE sessions SET time='1521829066503' WHERE token='+n68Dllx8Qt6deayjqEjK/19gfZN6n0DDy/vDO5EsW0%3D'
INSERT error: SQLITE_CONSTRAINT: UNIQUE constraint failed: sessions.token

```

**Comment by jonasess** [comment]
done it worked thanks

**Comment by jonasess** [comment]
what does RPC means? RPC address ,RPC user,RPC password?

**Comment by 3s3s** [comment]
If coins not added, try change this code
https://github.com/3s3s/opentrade/blob/master/static_pages/js/utils.js#L96

change
socket = new WebSocket("wss://"+window.location.host+ ":40443");

to
socket = new WebSocket("wss://"+window.location.hostname+ ":40443");

where port (40443) should be same as in this string
https://github.com/3s3s/opentrade/blob/master/server/constants.js#L16

**Comment by vitorgamer58** [comment]
lets go

```
Headers: {"access-control-allow-origin":"*","content-length":"86","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:false (message: Method not found<br> )
Status: 200
Headers: {"content-length":"86","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:false (message: Method not found<br> )
rpcPostJSON {"jsonrpc": "1.0", "id":"curltest", "method": "getbalance", "params": ["921eae7cb1d954364dcead329cf2e983",0] }
rpcPostJSON {"jsonrpc": "1.0", "id":"curltest", "method": "getbalance", "params": ["921eae7cb1d954364dcead329cf2e983",0] }
Status: 200
Headers: {"access-control-allow-origin":"*","content-length":"84","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:success (message:  )
Status: 200
Headers: {"content-length":"99","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:success (message:  )
```
I was able to add the coins, but I could not make a deposit because the address is not generated.

**Comment by vitorgamer58** [comment]
and
![alt](http://ap.imagensbrasil.org/images/2018/03/23/Screenshot_514.png)

**Comment by 3s3s** [comment]
I am afraid CryptoNote RPC is not compatible with Bitcoin RPC. 
Currently OpenTrade support only Bitcoin forks that have compatibility with Bitcoin RPC https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

**Comment by jonasess** [comment]
Guys what does RPC means? and using RCP means we don't need daemon of the coin?

**Comment by 3s3s** [comment]
RPC is "Remote Procedure Calls"
Daemons have in-build RPC. About Bitcoin RPC you can read here:
https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)
and here
https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

**Comment by jonasess** [comment]
Thanks i will check it

**Comment by charnasol** [comment]
Are the rpc username and pass actually needed for all? And we will do the code in to make sure any tokens and cryptonote will work also.

**Comment by 3s3s** [comment]
There is strongly recommended to use rpc password for security reasons

**Comment by charnasol** [comment]
But not needed to list coins or add markets.

**Comment by vitorgamer58** [comment]
putz, my goal would be to only add cryptonight coins ..

**Comment by jonasess** [comment]
Hello whenever i try to add new coin using admin account i get this error in the console s://www.example.com:40443/' failed: Establishing a tunnel via proxy server failed.
Although  i changed the port in conastant.js to 443 . is there any other file which i have to change port in it also?

**Comment by jonasess** [comment]
Do you have any idea about this error : [DOM] Found 2 elements with non-unique id #inputUser
When i visit the coin page where we can add coin it shows in the console

**Comment by charnasol** [comment]
We have the coins added but the wallets do not show... 
And can outside API's be plugged is as a way of adding coins?

**Comment by charnasol** [comment]
Can anyone answer why wallet address does not show if we added a btc related coin?

**Comment by jonasess** [comment]
Hello . i set up the daemon is there any way to confirm that it's connected with the board?
And how to show the wallets address?

**Comment by tzman89** [comment]
@charnasol 
Check your bitcoin.conf and see if you have included server=1, deamon=1 and txindex=1
Those are for allowing RPC commands and transactions.

**Comment by jonasess** [comment]
@tzman89 these are the lines exist in the btcatom.conf
rpcuser=testuseratome
rpcpassword=testpassword
rpcport=7332
server=1
daemon=1
listen=1
and i ran the daemon on my server by typing the comand ./atom (let's say my server ip address is 199.87.90.15)

in open trade i put these information
RPC address : http://199.87.90.15 :7332
rpcuser=testuseratome
rpcpassword=testpassword

but still am getting same error
problem with request: connect ECONNREFUSED 199.87.90.15 :7332

**Comment by jonasess** [comment]
Also anyone has any idea about this error?

Error: listen EADDRINUSE :::40080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (/root/opentrade/server/main.js:31:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by vitorgamer58** [comment]
something is using port 40080, try using another port or giving a `sudo reboot` to restart your VPS.

**Comment by tzman89** [comment]
@jonasess 
you have a space betwen ip and port 
199.87.90.15 :7332
199.87.90.15:7332

**Comment by jonasess** [comment]
Guys anyone has any idea about this problem
I have a server was running another board using nginx configuration .
So i shut down nginx which mean that board will be off
I set up open trade board, i changed the prot to 443 so the open trade board will run on domain name then i run this command line (sudo -b node main.js) ti make open trade running in the background of the server and available all the time
But the problem is after a limited time 1 or 2 hours the processes of main.js die .
Is there any solution for that?

**Comment by charnasol** [comment]
@tzman89 since we are setting up our own boards, are they configured with a local wallet for commission or do we have to input that?

**Comment by jonasess** [comment]
Also is there anyway to change or add more VS coin? because it's only exchange with MC coin
Where i can add or change? in which files i should look up for?

**Comment by tzman89** [comment]
Just to clarify something, I saw this script 2 days ago and I went trought code.All I learned about opentrade is from the last 2 days which means stuff I say doesn't mean is true.I just want to help.

@jonasess 
Don't run it in the background, install screen and you can manage it in more windows.
With this you can close your terminal and it will still run, when you are back you just write screen -r and you are back into your windows where it's running.

@charnasol 
It's automated commision and it's done by database.Main wallet is doing everything and it's only wallet and commisions are whats left in main wallet after all users withdraw their coins.

@jonasess 
Yes you can easly change it by changing config in constants.js (just change from MC to Bitcoin or any coin you want) but as I can see there is not option to add more than one coin pair for now.

**Comment by jonasess** [comment]
@tzman89 i used forever to run it
and regarding changing the cased coin , i did it yesterday i just changed to bitcoin (btc) but does it means it will run automatically? or it needs more configurations?

**Comment by tzman89** [comment]
It will run automaticly, just be sure you have added Bitcoin and not bitcoin (capital B).If you can see balance bitcoin in buy order box then it's working.Also on market you won't have BTC since its now pair for all other coins

**Comment by jonasess** [comment]
Okay thank you

**Comment by tzman89** [comment]
it will be like this

![untitled](https://user-images.githubusercontent.com/35830811/38164280-119bef56-3502-11e8-828e-8f9dc90e5b7b.png)

**Comment by jonasess** [comment]
@tzman89  in constant.js i changed these two lines
exports.TRADE_MAIN_COIN = "Bitcoin";
exports.TRADE_MAIN_COIN_TICKER = "BTC";
But no changes yet .
It doesn't show up in market
Also in admin aria / coin i added bitcoin there and tested it using RPC and it's working
But still does't show on the title of market

**Comment by tzman89** [comment]
It will not show on the title, on the picture I changed it by myself in the code
You need to add one more coin and that coin will show in market, after clicking on it you will have an option to buy sell order

**Comment by jonasess** [comment]
@tzman89 does it means i don't have to set up the bitcoin daemon? and link it with RPC in admin->coin aria or i have to do that but make the bitcoin invisible . like not showing it?
Because making it invisible means the users will not get BTC wallet addresses .

**Comment by tzman89** [comment]
When you setup your deamon and add Bitcoin to admin panel, bitcoin wont show in market if it's added as main pair

**Comment by jonasess** [comment]
@tzman89  Okay i got you thanks for the help

**Comment by vitorgamer58** [comment]
@3s3s Would you have any tips on what file I should modify so opentrade would become compatible with cryptonight coins?

**Comment by jonasess** [comment]
@vitorgamer58 i added cryptonote (Galaxycash ... etc) successfully on the board like any other coin (btc ... etc).
Did you try to add it first?

**Comment by tzman89** [comment]
@jonasess 
GalaxyCash is bitcoin based coin with rpc 1.0
Try to add monero or bytecoin and you will see that this wont work.Cryptonote coins have different rpc commands and wont work with this script.

@vitorgamer58 
You will need to change alot of files if you want to add cryptonote

**Comment by charnasol** [comment]
@tzman89 what files as it would be worth it. Also how to change to make sure you can add tokens from ethereum and stellar and multichain...

**Comment by jonasess** [comment]
@tzman89 okay i got you.
Is there any simple code on js on how to send RPC request and get the results?
Like send request to server which running the daemon to get new wallet address, balance ... etc? since am new in rpc i would like to see some examples.

**Comment by tzman89** [comment]
@charnasol 
You will need one more rpc file,wallet file, new database fields with identification for all coins.
Wallet is the main in whole script, when you deposit coins those will be the same as all other on the trading page.So you need to make new wallet.js and rpc.js file, in wallet there are stored rpc commands and wallet is comunicating with rpc file.Check those 2 files and you will know what to do.

ERC20 is whole another story and I'm not very familiar with it.It's comunicating with external wallets and commands.

@jonasess 
There is no simple code, for any other coin which is not based on bitcoin you'll need to do a lot of programming.Not all coins work with RPC, crpytonote is one which works but have different commands for get address and send coins

**Comment by vitorgamer58** [comment]
@jonasess yes, I tried and got an error already documented above, probably cryptonote support has been added since the version I tried.
```
Headers: {"access-control-allow-origin":"*","content-length":"86","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:false (message: Method not found<br> )
Status: 200
Headers: {"content-length":"86","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:false (message: Method not found<br> )
rpcPostJSON {"jsonrpc": "1.0", "id":"curltest", "method": "getbalance", "params": ["921eae7cb1d954364dcead329cf2e983",0] }
rpcPostJSON {"jsonrpc": "1.0", "id":"curltest", "method": "getbalance", "params": ["921eae7cb1d954364dcead329cf2e983",0] }
Status: 200
Headers: {"access-control-allow-origin":"*","content-length":"84","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:success (message:  )
Status: 200
Headers: {"content-length":"99","server":"CryptoNote-based HTTP server"}
rpcPostJSON: result:success (message:  )
```

**Comment by jonasess** [comment]
@tzman89 Am not asking for other coin am asking for a simple code for a bitcoin, how to connect to daemon get an address and balance ...etc . i just need a simple code if it's available for bitcoin to understand rpc more.

**Comment by jonasess** [comment]
@vitorgamer58 True it's not supported . does it mean you have to add more codes or just simple changes to be supported?

**Comment by vitorgamer58** [comment]
But if it is not supported how did you add a cryptonote?

**Comment by jonasess** [comment]
i found what i was looking for on how to connect to daemon using rpc
you can send this curl request
curl --user username:password --data-binary '{"jsonrpc": "1", "id":"", "method": "getblockchaininfo", "params": [] }' -H 'content-type: text/plain' http://localhost:8332/

**Comment by jonasess** [comment]
Also can you guys tell me or direct me where i can find the other method to communicate with daemon?
there's getblockchaininfo, getbalance . what's the other methods? and what's their parameters?
For example getbalance what's it's parameters to get the balance of specific address ... etc

**Comment by jonasess** [comment]
I found here all the methods https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list
getnewaddress for getting new bitcoin wallet . but how to get it's passphrase?
I think it's needed to send money

**Comment by tzman89** [comment]
bitcoin-cli encrypwallet yourpassword
password you put will be your passphrase
You can get all commands by typing bitcoin-cli help

**Comment by jonasess** [comment]
@tzman89  encryptwallet "passphrase" does this command line apply on all addresses generated by the daemon? because it doesn't give an option to generate passphrase for ever address you generate.
Also is you used dumpprivkey it shows every address it's secrete key . where exactly you can use that secret key, because from what i see in transaction (exchange) you just need the address from both wallets not the secrete key.
Btw the dumpprivkey works with other daemons like bitcoin atom and galaxycash but it didn't work with bitcoin daemon as it asks for the passphrase of the address . which you don't get when you use getnewaddress to generate new one.

**Comment by morawskiwincenty9** [comment]
mx resolved:  [ { exchange: 'mx01.mail.com', priority: 10 },
  { exchange: 'mx00.mail.com', priority: 10 } ]
MX connection created:  mx01.mail.com
recv email.com>554-mail.com (mxgmxus001) Nemesis ESMTP Service not available
recv email.com>554-No SMTP service
recv email.com>554 invalid DNS PTR resource record, IP=56.101.50.77
SMTP responds error code 554
Error with your mail server: SMTP code:554 msg:554-mail.com (mxgmxus001) Nemesis ESMTP Service not available
554-No SMTP service
554 invalid DNS PTR resource record, IP=56.101.50.77
