### ISSUE TITLE
Error sudo nodejs main.js

### ISSUE THREAD

**Issue by lightrain125** [3s3s/opentrade#101]
Error: listen EADDRINUSE :::40080
at Server.setupListenHandle [as _listen2] (net.js:1334:14)
at listenInCluster (net.js:1382:12)
at Server.listen (net.js:1469:7)
at Object. (/root/opentrade/server/main.js:37:31)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
Error: listen EADDRINUSE :::40443
at Server.setupListenHandle [as _listen2] (net.js:1334:14)
at listenInCluster (net.js:1382:12)
at Server.listen (net.js:1469:7)
at Object. (/root/opentrade/server/main.js:38:33)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

Please help

**Comment by jonn4y** [comment]
Error: listen EADDRINUSE :::40080

&

Error: listen EADDRINUSE :::40443

tell you the addresses 40080 and 40443 (ssl port) are already running, are you already running the nodejs?

find out whats running and cancel it.

or as a last resort use 'killall -9 node'

**Comment by jonn4y** [comment]
@lightrain125 did this fix the issue? if so please close the issue

**Comment by aminaqi** [comment]
please help me i can't setup it
i'm running droplet ubunta 16 on digitalocean

![untitled](https://user-images.githubusercontent.com/42599315/45033263-38744a00-b069-11e8-9d66-2e6dfaa2f368.png)

**Comment by lightrain125** [comment]
I have not installed yet. Who can help me install step by step? It seems that readme.md is too outdated.

**Comment by CryptorClub** [comment]
`lsof -i tcp:40080`
get process id
`kill -9 ===processid===`

**Comment by Tr0j4n9** [comment]
You already have a process running on that port. Try rebooting?

**Comment by CryptorClub** [comment]
Reboot can help not always. My command works 99% success. Also Better to change to 80 port in constants.js file

**Comment by Tr0j4n9** [comment]
> please help me i can't setup it
> i'm running droplet ubunta 16 on digitalocean
> 
> ![untitled](https://user-images.githubusercontent.com/42599315/45033263-38744a00-b069-11e8-9d66-2e6dfaa2f368.png)

You must run `npm install` in that directory. You can join my Discord for direct help. https://discord.gg/fEYMcvX

**Comment by saydulk** [comment]
![screenshot from 2019-02-07 04-55-42](https://user-images.githubusercontent.com/1058663/52379923-1bb7c480-2a96-11e9-951c-4ec67a0f20a8.png)
same problem

**Comment by saydulk** [comment]
This will fix your problem:

forever start --minUptime 1000 --spinSleepTime 1000 main.js
