### ISSUE TITLE
Node Main.js Error

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#128]
```
opentrade/server$ node main.js
module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/kartx/Downloads/opentrade/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node: file too short
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kartx/Downloads/opentrade/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by daygle** [comment]
I think this is happening to me too...

**Comment by knkrth** [comment]
Still no luck, Same errot :( 

```
opentrade/server$ sudo node main.js 
[sudo] password for kartx: 
module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/kartx/Downloads/opentrade/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node: file too short
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kartx/Downloads/opentrade/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by knkrth** [comment]
After removing the opentrade folder by `rm -rf opentrade` & git clone again `git clone https://github.com/3s3s/opentrade.git
`  fix the problem.
