### ISSUE TITLE
New error while attempting to withdraw - ReferenceError: badBalances is not defined

### ISSUE THREAD

**Issue by TheRealHotSwap** [3s3s/opentrade#142]
Started to receive this error after the recent update. I did start fresh with a new database just to make sure.

ReferenceError: badBalances is not defined
    at Timeout.GetBalanceForWithdraw.g_constants.dbTables.balance.selectAll [as _onTimeout] (/opentrade/server/modules/users/wallet.js:464:19)
    at ontimeout (timers.js:505:15)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by TheRealHotSwap** [comment]
Found the error, thanks!
