### ISSUE TITLE
node main.js error

### ISSUE THREAD

**Issue by Marchay** [3s3s/opentrade#167]
When I try `node main.js`
It responds with `mx resolved:  [ { exchange: 'mx00.mail.com', priority: 10 },
  { exchange: 'mx01.mail.com', priority: 10 } ]
MX connection created:  mx00.mail.com
recv email.com>554-mail.com (mxgmxus002) Nemesis ESMTP Service not available
recv email.com>554-No SMTP service
recv email.com>554 invalid DNS PTR resource record, IP=142.93.220.147
SMTP responds error code 554` How to fix

**Comment by jonn4y** [comment]
this has been answered countless times, please search through the closed issues for the answers

**Comment by Marchay** [comment]
Any solution for this?

**Comment by knkrth** [comment]
Remove `node_module` folder & Try run `sudo npm i` again. If the problem still exists, Remove opentrade folder & `git clone https://github.com/3s3s/opentrade`

**Comment by Liguf** [comment]
@knkrth I have an error `error on connectMx Error: queryMx ENODATA primex.xyz
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:244:19)`

**Comment by knkrth** [comment]
Change it https://github.com/3s3s/opentrade/blob/master/server/constants.js#L19 to `disabled`

**Comment by Liguf** [comment]
Now new error `error on connectMx Error: queryMx ENODATA primex.xyz
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:244:19)`

**Comment by Liguf** [comment]
New Error `events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::40080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/root/opentrade/server/main.js:38:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

**Comment by Liguf** [comment]
@knkrth I changed port from 40080 to 80 constants.js and still got error `events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/root/opentrade/server/main.js:38:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

**Comment by Liguf** [comment]
@knkrth Getting same error :/

**Comment by knkrth** [comment]
It seems like DNS error check your DNS & Your web address provider DNS.

**Comment by Liguf** [comment]
I am hosting on digitalocean is that an issue?

**Comment by knkrth** [comment]
No. You are using a website address as `websitex.xyz` check your domain DNS settings.

**Comment by Liguf** [comment]
But I want to test on localmachine how to?

**Comment by knkrth** [comment]
After running `node main.js` go to https://<your-digitalocean-ipaddress>:40443

**Comment by Liguf** [comment]
@knkrth It keeps loading forever

**Comment by Liguf** [comment]
@knkrth https://142.93.34.243:443

**Comment by Liguf** [comment]
@knkrth New error events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::40080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/root/opentrade/server/main.js:38:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by knkrth** [comment]
@Liguf Destroy your digitalocean droplet & create a new ubuntu 16 x64 droplet

After the fresh install follow these steps below,

```
sudo apt-get update
sudo apt-get install build-essential libssl-dev curl -y

curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt-get install nodejs

git clone https://github.com/3s3s/opentrade.git
cd opentrade
sudo npm install 

cd server
sudo node main.js
```

**Comment by Liguf** [comment]
sudo node main.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::40080
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Object.<anonymous> (/root/opentrade/server/main.js:38:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)



Give you'r discord so we can talk there

**Comment by Liguf** [comment]
It seems other errors are fixed but this new one 
error on connectMx Error: queryMx ESERVFAIL primex.xyz
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:213:19)
/root/opentrade/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

Error: unexpected init db error 1
    at /root/opentrade/server/database.js:210:28
    at onEndOne (/root/opentrade/server/utils.js:211:13)
    at Statement.<anonymous> (/root/opentrade/server/database.js:56:13)
--> in Database#run('CREATE TABLE IF NOT EXISTS users (login TEXT UNIQUE, email TEXT UNIQUE, password TEXT, info TEXT, PRIMARY KEY (login, email))', [Function])
    at CreateTable (/root/opentrade/server/database.js:48:15)
    at Run (/root/opentrade/server/utils.js:192:9)
    at /root/opentrade/server/utils.js:218:21
    at /root/opentrade/server/database.js:264:13
    at onEndOne (/root/opentrade/server/utils.js:211:13)
    at Statement.<anonymous> (/root/opentrade/server/database.js:51:17)

Give discord so we can talk

**Comment by knkrth** [comment]
@Liguf My discord handle is same as @knkrth

**Comment by Liguf** [comment]
The four digits after name?

**Comment by knkrth** [comment]
Join here https://discord.gg/K4Tm4SP
