### ISSUE TITLE
UI rendering of demo site https://trade.multicoins.org/

### ISSUE THREAD

**Issue by archana209** [3s3s/opentrade#20]
I find the rendering all over the place when I open 
https://trade.multicoins.org/

My local instance is showing the same layout as well.
Anyone else observed the same.
If its an issue or stylesheet or something please let me know

**Comment by andrux2016** [comment]
i cant get this to lunch

:~/opentrade/server# node main.js
_tls_common.js:66
      c.context.setCert(options.cert);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:66:17)
    at Server (_tls_wrap.js:745:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:47:10)
    at Object.<anonymous> (/root/opentrade/server/main.js:29:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
