### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:40543

### ISSUE THREAD

**Issue by DigitalCoin1** [3s3s/opentrade#221]
I am getting this error when starting Exchange, could you let me know what it is?

```
SSL Proxy listening on port 443
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:40543
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
Emitted 'error' event at:
    at ClientRequest.req.on (/home/spero/opentrade/node_modules/ws/lib/websocket.js:551:10)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by DigitalCoin1** [comment]
Sorry but it was a temporary problem with the SQLITE3 server, I restarted main.js from the database and everything is ok.

**Comment by dhhhfgnvn** [comment]
@DigitalCoin1 
Hi , I'm having the same problem as you did and i dont understand your solution.Can you please explain to me how you managed to solve it.Thanks i'm very grateful for your time 🙏
