### ISSUE TITLE
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by marquis-ogre** [3s3s/opentrade#249]
I have a error after installing the Opentrade in a fresh VPS, the error is 

root@OPENTRADE:~/opentrade/server# node main.js
_tls_common.js:89
      c.context.setCert(options.cert);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:89:17)
    at Server (_tls_wrap.js:794:25)
    at new Server (https.js:48:14)
    at Object.createServer (https.js:70:10)
    at Object.<anonymous> (/root/opentrade/server/main.js:35:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by Brewin95** [comment]
are you trying to start the exchange if so node main.js doesn't work do 

`forever start main.js`

**Comment by Xerxes7777** [comment]
I have the same problem. the node main.js command does not work
forever start main.js  is entered but the website which was working before 
forever start main.js is not working now.
how do you start the website now??

**Comment by Xerxes7777** [comment]
I figured it out. It was fullchain.pem and privkey.pem SSL file that I updated when I went back to the old copy the website started working again. Nothing do with command  forever start main.js
