### ISSUE TITLE
Error email 

### ISSUE THREAD

**Issue by CarmeloCampos** [3s3s/opentrade#256]
When I put "node main.js" in / server / and place a custom email in the constans.js, I get the following error:
``
SSL Proxy listening on port 443
mx resolved:
rest::getJSON
localhost:200
Error on connectMx for:  { exchange: 'mail.olivos.com.pe', priority: 0 } { Error: connect ETIMEDOUT 186.64.119.195:25
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '186.64.119.195',
  port: 25 }
error on connectMx Error: can not connect to any SMTP server
    at tryConnect (/root/CryptoVen/node_modules/sendmail/sendmail.js:88:49)
    at Socket.<anonymous> (/root/CryptoVen/node_modules/sendmail/sendmail.js:94:13)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Error with your mail server: can not connect to any SMTP server
``

**Comment by CarmeloCampos** [comment]
When you left the mail configuration by default, the following message comes out: ```
SSL Proxy listening on port 443
mx resolved:
rest::getJSON
localhost:200

```
I'm missing something?

**Comment by eduardofacunha** [comment]
Same here.

**Comment by gnark-mining** [comment]
Did you solve it ? 

ty

**Comment by 3s3s** [comment]
What about the topic at the top? Is it not help? https://github.com/3s3s/opentrade/issues/319
