### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#266]
```
opentrade/accountsserver$ node main.js 
/home/ubuntu/workspace/opentrade/accountsserver/database.js:14
    return new Promise(async ok => {
                       ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/opentrade/accountsserver/main.js:69:1)
Node NOT Exiting...
```

**Comment by knkrth** [comment]
```
opentrade/server (master) $ node main.js 
/home/ubuntu/workspace/opentrade/server/database.js:161
exports.Init = async function(callback)
                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/opentrade/server/main.js:106:1)
```

**Comment by DigitalCoin1** [comment]
The same here:

![image](https://user-images.githubusercontent.com/32315718/57481999-e16ae880-7279-11e9-8e47-aa46330b0b69.png)


![image](https://user-images.githubusercontent.com/32315718/57482013-ea5bba00-7279-11e9-8ce3-165df1d1cc0e.png)

![image](https://user-images.githubusercontent.com/32315718/57482031-f5164f00-7279-11e9-993f-5016907ce79c.png)
