### ISSUE TITLE
Unhandled 'error' event (js: 182 )

### ISSUE THREAD

**Issue by padynka** [3s3s/opentrade#268]
@3s3s 
In the end of installation i have next error:
`~/opentrade/server# node main.js
events.js:182

      throw er; // Unhandled 'error' event

      ^

Error: listen EADDRINUSE :::80

    at Object.exports._errnoException (util.js:1026:11)

    at exports._exceptionWithHostPort (util.js:1049:20)

    at Server.setupListenHandle [as _listen2] (net.js:1305:14)

    at listenInCluster (net.js:1353:12)

    at Server.listen (net.js:1453:7)

    at Object.<anonymous> (/root/opentrade/server/main.js:37:31)

    at Module._compile (module.js:569:30)

    at Object.Module._extensions..js (module.js:580:10)

    at Module.load (module.js:503:32)

    at tryModuleLoad (module.js:466:12)`

**Comment by padynka** [comment]
`SSL Proxy listening on port 443
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:40545
at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)`

**Comment by dhhhfgnvn** [comment]
@padynka  How did you managed to solve it ?

**Comment by xcelr** [comment]
@StelicaRusu @padynka How did you guys solve this issue?
