### ISSUE TITLE
Errors Node Main.js

### ISSUE THREAD

**Issue by Brewin95** [3s3s/opentrade#279]
Datebase Error

`Error: listen EADDRINUSE :::40545
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/root/opentrade/databaseServer/main.js:35:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
Node NOT Exiting...`

Accounts Database Error

`root@ubuntu:~/opentrade/databaseServer# cd ~/opentrade/accountsserver
root@ubuntu:~/opentrade/accountsserver# node main.js
Error: listen EADDRINUSE :::40745
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/root/opentrade/accountsserver/main.js:34:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

Server Error
`root@ubuntu:~/opentrade/server# node main.js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/root/opentrade/server/main.js:37:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

Debug File In Accounts database Server Says This

`Error: unexpected init db error 1
    at g_utils.ForEachSync (/root/opentrade/accountsserver/database.js:386:28)
    at onEndOne (/root/opentrade/accountsserver/utils.js:69:13)
    at Timeout.CreateTable.err [as _onTimeout] (/root/opentrade/accountsserver/database.js:228:13)
    at ontimeout (timers.js:495:15)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)`

Debug Log In Database Folder
`Error: SQLITE_CANTOPEN: unable to open database file`

Error While Running RPC Test In Admin Panel

`"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /</pre>\n</body>\n</html>\n"
`

Any Help With These Errors Would Be Greatly Appreciated As Im Now At A Brick Wall And Don't How To Solve Them

**Comment by Brewin95** [comment]
@3s3s Any Help

**Comment by Brewin95** [comment]
Anyone?

**Comment by smoe** [comment]
Hello,
The two errors I consider to be unrelated. Please check out directory ~/.forever for better log files. I seem to have fixed the database access problem in https://github.com/3s3s/opentrade/issues/288 . Now I am where you are 
```
SSL Proxy listening on port 443
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
...skipping...
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error: Forever detected script exited with code: 1
error: Script restart attempt #98
SSL Proxy listening on port 443
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error: Forever detected script exited with code: 1
error: Script restart attempt #99
```
Sigh.

**Comment by smoe** [comment]
I seem to have solved it. It is more of these path issues. Say, you have the installation at
/home/thisisme/opentrade
then have symlinks to that directory from /home/opentrade and /root/opentrade.
