### ISSUE TITLE
Can't run databaseServer

### ISSUE THREAD

**Issue by oleksandrhinko** [3s3s/opentrade#286]
```
opentrade/databaseServer/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

```

**Comment by asystat** [comment]
I have the same issue. what was it? I suspect it's the open ports cause I'm executing the program behind docker...

**Comment by 3s3s** [comment]
Hi
may be latest websocket library is not compatible with node 8.0.0
try this https://github.com/3s3s/opentrade/pull/287/commits/04f53507936c7f23083ca0ced94701c7bb8026e3
or try to upgrade node.js

**Comment by oleksandrhinko** [comment]
Use "ws": "6.1.2" in your package.json.
Or better use https://github.com/rubykube/peatio

**Comment by asystat** [comment]
Thanks, it worked.
