### ISSUE TITLE
how to get smtp working

### ISSUE THREAD

**Issue by christophergidlof** [3s3s/opentrade#307]
hi i am getting this error when trying to create a user is there a way to manually set smtp server 

mx resolved: 
Error on connectMx for:  { exchange: 'outlook-com.olc.protection.outlook.com',
  priority: 5 } { Error: connect ETIMEDOUT 104.47.46.33:25
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.47.46.33',
  port: 25 }
error on connectMx Error: can not connect to any SMTP server
    at tryConnect (/home/user/opentrade/node_modules/sendmail/sendmail.js:90:49)
    at Socket.<anonymous> (/home/user/opentrade/node_modules/sendmail/sendmail.js:96:13)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

all i find is in constants.js 2 email adresses you can change no options for smtp server port user and password

**Comment by ExchangeTime** [comment]
You need to contact your VPS provider to open port 25 (always closed to prevent spam emails). @christophergidlof 

Incase you are looking for a new design, trading layout, pages or features.
Hit me up at gokryptoinfo@gmail.com

Advanced chart system & trading https://gyazo.com/f0751a43e8a4c0d675823521c2c2eda7
Advanced chart system & trading 2nd https://gyazo.com/697e405dad42eb9264dd342cffcfe6af
Main-page, https://gyazo.com/caa61a550807dfed53586fcf1a0d3d48
Sign-in page, https://gyazo.com/079ab81e0447a83536068dbaded3000d
sign-up page, https://gyazo.com/b391edc930bf6cf98690c65daaf00cc2
Live price display, https://gyazo.com/caa61a550807dfed53586fcf1a0d3d48 (at the end)
Comparison feature, on request
Wallet redesign, on request

**Comment by christophergidlof** [comment]
hi 
i know about port 25 and its open on my google vm 
but i wounder if i could use a different smtp-server if i type in smtp-server adress username and password in some config file
