### ISSUE TITLE
Youtube tutorial to setup  the exchange with Advanced trading layouts

### ISSUE THREAD

**Issue by ExchangeTime** [3s3s/opentrade#318]
Hello!

I have made my advanced trading layouts, mainpage, signup and signin page free!
Hope you enjoy my tutorials! Please subscribe & like for more videos!

https://www.youtube.com/watch?v=0D7tkobhPkI

**Comment by omardavinzi** [comment]
not works for me error. 
if (exports.password_private_suffix == 'LONG_RANDOM_STRING1') throw new Error('You MUST change default value exports.password_private_suffix !')
                                                              ^

Error: You MUST change default value exports.password_private_suffix !
    at Object.<anonymous> (/var/www/html/server/modules/private_constants.js:10:69)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/server/constants.js:237:25)
    at Module._compile (module.js:569:30)
root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/server/main.js:8:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/server/main.js:8:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/server/main.js:8:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root@omar-HP-ProBook-6550b:/var/www/html/server# forever start main.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: main.js
root@omar-HP-ProBook-6550b:/var/www/html/server# forever start main.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: main.js
root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/server/main.js:8:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by ExchangeTime** [comment]
> not works for me error.
> if (exports.password_private_suffix == 'LONG_RANDOM_STRING1') throw new Error('You MUST change default value exports.password_private_suffix !')
> ^
> 
> Error: You MUST change default value exports.password_private_suffix !
> at Object. (/var/www/html/server/modules/private_constants.js:10:69)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)
> at Function.Module._load (module.js:458:3)
> at Module.require (module.js:513:17)
> at require (internal/module.js:11:18)
> at Object. (/var/www/html/server/constants.js:237:25)
> at Module._compile (module.js:569:30)
> root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
> module.js:487
> throw err;
> ^
> 
> Error: Cannot find module 'express'
> at Function.Module._resolveFilename (module.js:485:15)
> at Function.Module._load (module.js:437:25)
> at Module.require (module.js:513:17)
> at require (internal/module.js:11:18)
> at Object. (/var/www/html/server/main.js:8:17)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)
> at Function.Module._load (module.js:458:3)
> root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
> module.js:487
> throw err;
> ^
> 
> Error: Cannot find module 'express'
> at Function.Module._resolveFilename (module.js:485:15)
> at Function.Module._load (module.js:437:25)
> at Module.require (module.js:513:17)
> at require (internal/module.js:11:18)
> at Object. (/var/www/html/server/main.js:8:17)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)
> at Function.Module._load (module.js:458:3)
> root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
> module.js:487
> throw err;
> ^
> 
> Error: Cannot find module 'express'
> at Function.Module._resolveFilename (module.js:485:15)
> at Function.Module._load (module.js:437:25)
> at Module.require (module.js:513:17)
> at require (internal/module.js:11:18)
> at Object. (/var/www/html/server/main.js:8:17)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)
> at Function.Module._load (module.js:458:3)
> root@omar-HP-ProBook-6550b:/var/www/html/server# forever start main.js
> warn: --minUptime not set. Defaulting to: 1000ms
> warn: --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
> info: Forever processing file: main.js
> root@omar-HP-ProBook-6550b:/var/www/html/server# forever start main.js
> warn: --minUptime not set. Defaulting to: 1000ms
> warn: --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
> info: Forever processing file: main.js
> root@omar-HP-ProBook-6550b:/var/www/html/server# node main.js
> module.js:487
> throw err;
> ^
> 
> Error: Cannot find module 'express'
> at Function.Module._resolveFilename (module.js:485:15)
> at Function.Module._load (module.js:437:25)
> at Module.require (module.js:513:17)
> at require (internal/module.js:11:18)
> at Object. (/var/www/html/server/main.js:8:17)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)
> at Function.Module._load (module.js:458:3)

it seriously explain exactly what u have done wrong in the error
