### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by sofiyaz** [3s3s/opentrade#321]
/root/ExchangePrivate2/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/ExchangePriv

**Comment by ExchangeTime** [comment]
Are you running it on localhost? @sofiyaz 
Contact me at gokryptoinfo@gmail.com and i try to help you solve it

**Comment by sofiyaz** [comment]
No I m running on my vps it's mendetory to change it

**Comment by sofiyaz** [comment]
I SEND YOU MAIL

**Comment by sofiyaz** [comment]
CAN U PLEASE REPLY ME ON MY MAIL

**Comment by 3s3s** [comment]
https://github.com/3s3s/opentrade/issues/286
