### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by sofiyaz** [3s3s/opentrade#322]
root@vps45676365:~/opentrade/server# node main.js
/root/opentrade/server/modules/private_constants.js:10
if (exports.password_private_suffix == '123456789jflsakjfl;sakjdfl;sakjdfkl;sajdfkl;sajdkjs') throw new Error('You MUST change default value exports.password_private_suffix !')
                                                                                              ^

Error: You MUST change default value exports.password_private_suffix !
    at Object.<anonymous> (/root/opentrade/server/modules/private_constants.js:10:101)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/root/opentrade/server/constants.js:237:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modul

**Comment by sofiyaz** [comment]
if anybody install it on my vps i give them my ip username and password

**Comment by AtomicLemon** [comment]
Try setting it to something like this: pNs3SPBB72tFLk5bMyzg9J5r6UYnaLJ5
So it contains no special characters like semicolons.
