### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by sofiyaz** [3s3s/opentrade#323]
root@vps45676365:~/ExchangePrivate2/server# node main.js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- /root/ExchangePrivate2/server/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/root/ExchangePrivate2/server/main.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/ExchangePrivate2/server/main.js' ]
}
root@vps45676365:~/ExchangePrivate2/server# .js:628internal/modules/cjs/loader.js:628

**Comment by AtomicLemon** [comment]
Have you tried running `npm install`?
