### ISSUE TITLE
getaccountaddress is deprecated and will be removed in V0.18. To use this command, start litecoind with -deprecatedrpc=accounts.

### ISSUE THREAD

**Issue by 22Developers** [3s3s/opentrade#328]
There are no specific instructions for fixing this error. Any help me?

SSL Proxy listening on port 443
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:343:15)
    at Socket.socketOnEnd (_http_client.js:435:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Thank you very much!

**Comment by gfijrb** [comment]
dont use deprecated commands on prod

**Comment by 3s3s** [comment]
accounts is moved to accountserver. Deprecated rpc are not using in OpenTrade a long time ago
