### ISSUE TITLE
after sudo node main.js,it is Error

### ISSUE THREAD

**Issue by a20180502** [3s3s/opentrade#331]
SSL Proxy listening on port 443
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:40545
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
Emitted 'error' event at:
    at ClientRequest.<anonymous> (/home/ubuntu/opentrade/node_modules/ws/lib/websocket.js:551:10)
    at ClientRequest.emit (events.js:203:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 40545

**Comment by xcelr** [comment]
Hey did you ever find a fix for this, im running into the same error.
