### ISSUE TITLE
accountsserver forever start main.js give error

### ISSUE THREAD

**Issue by Xerxes7777** [3s3s/opentrade#341]
After
cd ~/opentrade/databaseServer
[sudo] forever start main.js
it runs fine 
but 
cd ~/opentrade/accountsserver
git checkout master
[sudo] forever start main.js
Gives error from forever log:

Proxy listening on port 40745
Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at Socket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Node NOT Exiting...

(by the way 
cd  ~/opentrade/server
[sudo] forever start main.js
works ok)

SO the website is accessible coins are added but RPC command does not work in the web site such as getbalance.

Any Help??

**Comment by Xerxes7777** [comment]
I think I fixed it Error solved
/root/opentrade/accountsserver/constants.js
open this file edited domain from local host to your severe actual IP address

I also made sure the line below pointing to the right folder in the severe
DATABASE_PATH = '/root/opentrade/accountsserver/database/sqlite_accounts.db';
