### ISSUE TITLE
Accountsserver install Python .. py3 installed but no Joy.    "gyp ERR! configure error  gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by johnda98** [3s3s/opentrade#345]
Ivan/  team any thoughts ?   running in your recommended cloud instance
.. i even installed py3 after i  got error.. but it looks like a ENV not set ?

interestingly there was a process running in the session - not sure if it was the accounts server

CENSE         package-lock.json  server
root@ubuntu-s-4vcpu-8gb-nyc3-01:~/opentrade# npm install

> sqlite3@4.0.4 install /root/opentrade/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and node@12.6.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.4 and node@12.6.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
gyp ERR! System Linux 4.4.0-169-generic
gyp ERR! command "/root/.nvm/versions/node/v12.6.0/bin/node" "/root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/opentrade/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/opentrade/node_modules/sqlite3/lib/binding/node-v72-linux-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /root/opentrade/node_modules/sqlite3
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v12.6.0/bin/node /root/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --

**Comment by johnda98** [comment]
installed python3 exported path and  packages then installed - g
