### ISSUE TITLE
accountsserver main.js error: unexpected init db error 1

### ISSUE THREAD

**Issue by HugoPhoenix** [3s3s/opentrade#379]
~/opentrade/accountsserver# sudo node main.js
Error: unexpected init db error 1
    at /root/opentrade/accountsserver/database.js:446:28
    at onEndOne (/root/opentrade/accountsserver/utils.js:80:13)
    at Timeout._onTimeout (/root/opentrade/accountsserver/database.js:281:13)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7)

**Comment by HugoPhoenix** [comment]
@3s3s

**Comment by khanmos12** [comment]
Facing the same issue. How can it be resolved?

**Comment by alexeyneu** [comment]
https://github.com/alexeyneu/opentrade/blob/master/readme.md#build--2004

**Comment by yaboiroabi** [comment]
I am having this very same issue... please help me... @alexeyneu   @jonn4y  @benfavre  @smoe

**Comment by alexeyneu** [comment]
i mean https://github.com/alexeyneu/opentrade/blob/dc2f3367c0b16ef86e210656bd90047d999ac9ca/readme.md#build--2004
