### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by khanmos12** [3s3s/opentrade#380]
Error: unexpected init db error 1
    at /root/opentrade/accountsserver/database.js:446:28
    at onEndOne (/root/opentrade/accountsserver/utils.js:80:13)
    at Timeout._onTimeout (/root/opentrade/accountsserver/database.js:281:13)
    at listOnTimeout (internal/timers.js:533:17)
    at processTimers (internal/timers.js:475:7)

**Comment by yaboiroabi** [comment]
how is this issue fixed
