### ISSUE TITLE
node_sqlite fails to install

### ISSUE THREAD

**Issue by wbsmolen** [3s3s/opentrade#40]
```
2621 verbose stack Error: sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`

2621 verbose stack Exit status 126

2621 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)

2621 verbose stack     at emitTwo (events.js:106:13)

2621 verbose stack     at EventEmitter.emit (events.js:191:7)

2621 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)

2621 verbose stack     at emitTwo (events.js:106:13)

2621 verbose stack     at ChildProcess.emit (events.js:191:7)

2621 verbose stack     at maybeClose (internal/child_process.js:850:16)

2621 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

2625 error argv "/root/.nvm/versions/node/v6.0.0/bin/node" "/root/.nvm/versions/node/v6.0.0/bin/npm" "install"

2626 error node v6.0.0

2627 error npm  v3.8.6

2628 error code ELIFECYCLE

2629 error sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`

2629 error Exit status 126

2630 error Failed at the sqlite3@4.0.0 install script 'node-pre-gyp install --fallback-to-build'.
```

Any reason why we're using node 6.0.0?

**Comment by wbsmolen** [comment]
Running a vanilla install of node via apt-get worked. sudo: npm: was failing
