### ISSUE TITLE
Recaptcha failed

### ISSUE THREAD

**Issue by CryptorClub** [3s3s/opentrade#95]
Recaptcha failed error due the first user registration.
I setup secret key in "/root/opentrade/server/modules/private_constants.js" file
And pub key in "/root/opentrade/server/constants.js" file

Solve sql3 problem earlier and npm setup...
Also tried to clear cache 

Right now can't register, after ~1-2 minutes system redirect me on a page, where error:
```
Recaptcha failed
Something wrong ((

Please try again.
```

**Comment by jonn4y** [comment]
is your recaptcha set up correctly on googles side? have you entered the correct domain / IP that is the only time ive seen that issue

**Comment by CryptorClub** [comment]
@jonn4y, recaptcha shows me green check mark, that's verify me. One thing, that I do not do earlier, is I do not setup pub key intime, but right now is correct.

My feeling, that script is continue intallation, but do it too long until verification of recaptcha expired...1-2 minutes until I redirected to this error page

**Comment by jonn4y** [comment]
Try this:

Disable captcha  on this line:
https://github.com/3s3s/opentrade/blob/8fe73249d8a673d1794980bf05e094af8a4a4d69/server/constants.js#L15

then restart the server

Sign up your first account

re-enable captcha 

restart the server

check if you can login, then register a second user which captcha active and see if that works

**Comment by CryptorClub** [comment]
@jonn4y, thanks for this advice. Right now I see loading round.
At terminal see that script can't send email. My domain setuped on Google mail service.
Few last errors:
``Error on connectMx for:  { exchange: 'gmail-smtp-in.l.google.com', priority: 5 } { Error: connect ETIMEDOUT 64.233.167.27:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '64.233.167.27',
  port: 25 }
error on connectMx Error: can not connect to any SMTP server
    at tryConnect (/root/opentrade/node_modules/sendmail/sendmail.js:88:49)
    at Socket.<anonymous> (/root/opentrade/node_modules/sendmail/sendmail.js:94:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error on connectMx for:  { exchange: 'alt3.gmail-smtp-in.l.google.com', priority: 30 } { Error: connect ETIMEDOUT 108.177.125.27:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '108.177.125.27',
  port: 25 }
Error on connectMx for:  { exchange: 'alt2.gmail-smtp-in.l.google.com', priority: 20 } { Error: connect ETIMEDOUT 74.125.24.27:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.24.27',
  port: 25 }
Error on connectMx for:  { exchange: 'alt1.gmail-smtp-in.l.google.com', priority: 10 } { Error: connect ETIMEDOUT 64.233.164.26:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '64.233.164.26',
  port: 25 }
Error on connectMx for:  { exchange: 'gmail-smtp-in.l.google.com', priority: 5 } { Error: connect ETIMEDOUT 74.125.71.26:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.71.26',
  port: 25 }
error on connectMx Error: can not connect to any SMTP server
    at tryConnect (/root/opentrade/node_modules/sendmail/sendmail.js:88:49)
    at Socket.<anonymous> (/root/opentrade/node_modules/sendmail/sendmail.js:94:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
^C
root@greencoin:~/opentrade/server# sudo node main.js
Error on connectMx for:  { exchange: 'alt3.aspmx.l.google.com', priority: 10 } { Error: connect ETIMEDOUT 108.177.125.26:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
``

**Comment by CryptorClub** [comment]
@jonn4y thank for support. Right now I see, that script can't send email. Where I need to setup mail login details?

`  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '64.233.164.27',
  port: 25 }
Error on connectMx for:  { exchange: 'gmail-smtp-in.l.google.com', priority: 5 } { Error: connect ETIMEDOUT 74.125.71.26:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.71.26',
  port: 25 }
error on connectMx Error: can not connect to any SMTP server
    at tryConnect (/root/opentrade/node_modules/sendmail/sendmail.js:88:49)
    at Socket.<anonymous> (/root/opentrade/node_modules/sendmail/sendmail.js:94:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

`
