### ISSUE TITLE
Gsuite sendmail problem

### ISSUE THREAD

**Issue by CryptorClub** [3s3s/opentrade#96]
Script can't send email because of MX records directed to Google servers and its not configured. Can you help to setup right port, tls, login/pass?

```
Error on connectMx for:  { exchange: 'alt2.gmail-smtp-in.l.google.com', priority: 20 } { Error: connect ETIMEDOUT 74.125.24.27:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.24.27',
  port: 25 }
Error on connectMx for:  { exchange: 'alt1.gmail-smtp-in.l.google.com', priority: 10 } { Error: connect ETIMEDOUT 64.233.164.27:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '64.233.164.27',
  port: 25 }
Error on connectMx for:  { exchange: 'aspmx.l.google.com', priority: 1 } { Error: connect ETIMEDOUT 173.194.76.27:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '173.194.76.27',
  port: 25 }
error on connectMx Error: can not connect to any SMTP server
    at tryConnect (/root/opentrade/node_modules/sendmail/sendmail.js:88:49)
    at Socket.<anonymous> (/root/opentrade/node_modules/sendmail/sendmail.js:94:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by 3s3s** [comment]
https://github.com/3s3s/opentrade/issues/19

**Comment by CryptorClub** [comment]
I use Digital Ocean server. As I understand we need to use 465 port, "tls" secure and authentification.

**Comment by 3s3s** [comment]
OpenTrade does not support encrypted emails. Only standart SMTP.

**Comment by CryptorClub** [comment]
I found, that with google we can use smtp on port 25
https://support.google.com/a/answer/176600?hl=en

I modify /root/opentrade/node_modules/sendmail/sendmail.js on 25 line with
`  const smtpHost = options.smtpHost || 'smtp-relay.gmail.com';`
But its not affect. I've setup OpenTrade on fresh VPS on Digital Ocean. Strange that I got this problem. I need to try change ip?

**Comment by 3s3s** [comment]
Who is your email provider? No one had any problems with gmail,. Try to use gmail.

**Comment by CryptorClub** [comment]
I use gmail account for registration. 

But on the domain, where I setup script exist MX records, and script use them to send email that forwarded to Googles servers without authorization. Its not like php mail() function without authentication. Its tried to connect to external servers...

**Comment by CryptorClub** [comment]
Maybe we need to modify this lines 159 -165
in file /root/opentrade/node_modules/sendmail/sendmail.js
`        /*
         if(mail.user && mail.pass){
           queue.push('AUTH LOGIN');
           login.push(new Buffer(mail.user).toString("base64"));
           login.push(new Buffer(mail.pass).toString("base64"));
         }
         */`

**Comment by CarmeloCampos** [comment]
How can I change port 25 for the one due?
